version: '3'
services:
  postgres_db:
    container_name: 'postgtres_db'
    image: postgres:latest
    # restart: always
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - '5432:5432'
    env_file:
      - sql.env
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
  server:
    container_name: marketplace_server
    build: .
    ports:
    - '3000:3000'