version: '3'
services:
  sql_db:
    container_name: 'sql_db'
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    env_file:
      - sql.env
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
  server:
    container_name: marketplace_server
    build: .
    ports:
    - '3000:3000'